version: "3.9"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - node
